CORE_OBJECTS := \
    $(CORE_DIR)/Core/include/core/arm/skyeye_common/vfp/vfpinstr.o \
    $(CORE_DIR)/Core/common/thread.o \
    $(CORE_DIR)/Core/common/play_time_manager.o \
    $(CORE_DIR)/Core/common/microprofile.o \
    $(CORE_DIR)/Core/common/texture.o \
    $(CORE_DIR)/Core/common/memory_detect.o \
    $(CORE_DIR)/Core/common/detached_tasks.o \
    $(CORE_DIR)/Core/common/settings.o \
    $(CORE_DIR)/Core/common/cityhash.o \
    $(CORE_DIR)/Core/common/zstd_compression.o \
    $(CORE_DIR)/Core/common/param_package.o \
    $(CORE_DIR)/Core/common/string_util.o \
    $(CORE_DIR)/Core/common/math_util.o \
    $(CORE_DIR)/Core/common/file_util.o \
    $(CORE_DIR)/Core/common/timer.o \
    $(CORE_DIR)/Core/common/scm_rev.o \
    $(CORE_DIR)/Core/common/memory_ref.o \
    $(CORE_DIR)/Core/common/error.o \
    $(CORE_DIR)/Core/common/hacks/hack_manager.o \
    $(CORE_DIR)/Core/common/hacks/hack_list.o \
    $(CORE_DIR)/Core/common/dynamic_library/dynamic_library.o \
    $(CORE_DIR)/Core/common/logging/backend.o \
    $(CORE_DIR)/Core/common/logging/text_formatter.o \
    $(CORE_DIR)/Core/common/logging/filter.o \
    $(CORE_DIR)/Core/common/aarch64/cpu_detect.o \
    $(CORE_DIR)/Core/video_core/right_eye_disabler.o \
    $(CORE_DIR)/Core/video_core/gpu.o \
    $(CORE_DIR)/Core/video_core/video_core.o \
    $(CORE_DIR)/Core/video_core/rasterizer_accelerated.o \
    $(CORE_DIR)/Core/video_core/renderer_base.o \
    $(CORE_DIR)/Core/video_core/texture/texture_decode.o \
    $(CORE_DIR)/Core/video_core/texture/etc1.o \
    $(CORE_DIR)/Core/video_core/pica/vertex_loader.o \
    $(CORE_DIR)/Core/video_core/pica/shader_unit.o \
    $(CORE_DIR)/Core/video_core/pica/output_vertex.o \
    $(CORE_DIR)/Core/video_core/pica/shader_setup.o \
    $(CORE_DIR)/Core/video_core/pica/pica_core.o \
    $(CORE_DIR)/Core/video_core/pica/regs_internal.o \
    $(CORE_DIR)/Core/video_core/pica/geometry_pipeline.o \
    $(CORE_DIR)/Core/video_core/pica/primitive_assembly.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_rasterizer.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_framebuffer.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_proctex.o \
    $(CORE_DIR)/Core/video_core/renderer_software/renderer_software.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_clipper.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_texturing.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_blitter.o \
    $(CORE_DIR)/Core/video_core/renderer_software/sw_lighting.o \
    $(CORE_DIR)/Core/video_core/shader/shader.o \
    $(CORE_DIR)/Core/video_core/shader/shader_interpreter.o \
    $(CORE_DIR)/Core/video_core/shader/generator/shader_gen.o \
    $(CORE_DIR)/Core/video_core/shader/generator/glsl_shader_decompiler.o \
    $(CORE_DIR)/Core/video_core/shader/generator/shader_uniforms.o \
    $(CORE_DIR)/Core/video_core/shader/generator/glsl_fs_shader_gen.o \
    $(CORE_DIR)/Core/video_core/shader/generator/glsl_shader_gen.o \
    $(CORE_DIR)/Core/video_core/shader/generator/pica_fs_config.o \
    $(CORE_DIR)/Core/video_core/debug_utils/debug_utils.o \
    $(CORE_DIR)/Core/video_core/rasterizer_cache/surface_base.o \
    $(CORE_DIR)/Core/video_core/rasterizer_cache/pixel_format.o \
    $(CORE_DIR)/Core/video_core/rasterizer_cache/utils.o \
    $(CORE_DIR)/Core/video_core/rasterizer_cache/surface_params.o \
    $(CORE_DIR)/Core/video_core/rasterizer_cache/rasterizer_cache.o \
    $(CORE_DIR)/Core/video_core/custom_textures/custom_format.o \
    $(CORE_DIR)/Core/video_core/custom_textures/custom_tex_manager.o \
    $(CORE_DIR)/Core/video_core/custom_textures/material.o \
    $(CORE_DIR)/Core/audio_core/interpolate.o \
    $(CORE_DIR)/Core/audio_core/static_input.o \
    $(CORE_DIR)/Core/audio_core/codec.o \
    $(CORE_DIR)/Core/audio_core/input_details.o \
    $(CORE_DIR)/Core/audio_core/time_stretch.o \
    $(CORE_DIR)/Core/audio_core/dsp_interface.o \
    $(CORE_DIR)/Core/audio_core/sink_details.o \
    $(CORE_DIR)/Core/audio_core/hle/hle.o \
    $(CORE_DIR)/Core/audio_core/hle/source.o \
    $(CORE_DIR)/Core/audio_core/hle/mixers.o \
    $(CORE_DIR)/Core/audio_core/hle/aac_decoder.o \
    $(CORE_DIR)/Core/audio_core/hle/filter.o \
    $(CORE_DIR)/Core/audio_core/hle/decoder.o \
    $(CORE_DIR)/Core/audio_core/lle/lle.o \
    $(CORE_DIR)/Core/input_common/main.o \
    $(CORE_DIR)/Core/input_common/touch_from_button.o \
    $(CORE_DIR)/Core/input_common/motion_emu.o \
    $(CORE_DIR)/Core/input_common/analog_from_button.o \
    $(CORE_DIR)/Core/input_common/keyboard.o \
    $(CORE_DIR)/Core/input_common/udp/udp.o \
    $(CORE_DIR)/Core/input_common/udp/protocol.o \
    $(CORE_DIR)/Core/input_common/udp/client.o \
    $(CORE_DIR)/Core/core/perf_stats.o \
    $(CORE_DIR)/Core/core/core.o \
    $(CORE_DIR)/Core/core/system_titles.o \
    $(CORE_DIR)/Core/core/core_timing.o \
    $(CORE_DIR)/Core/core/movie.o \
    $(CORE_DIR)/Core/core/savestate.o \
    $(CORE_DIR)/Core/core/nus_download.o \
    $(CORE_DIR)/Core/core/memory.o \
    $(CORE_DIR)/Core/core/rpc/packet.o \
    $(CORE_DIR)/Core/core/rpc/server.o \
    $(CORE_DIR)/Core/core/rpc/rpc_server.o \
    $(CORE_DIR)/Core/core/rpc/udp_server.o \
    $(CORE_DIR)/Core/core/hw/unique_data.o \
    $(CORE_DIR)/Core/core/hw/y2r.o \
    $(CORE_DIR)/Core/core/hw/ecc.o \
    $(CORE_DIR)/Core/core/hw/rsa/rsa.o \
    $(CORE_DIR)/Core/core/hw/aes/ccm.o \
    $(CORE_DIR)/Core/core/hw/aes/key.o \
    $(CORE_DIR)/Core/core/hw/aes/arithmetic128.o \
    $(CORE_DIR)/Core/core/loader/elf.o \
    $(CORE_DIR)/Core/core/loader/loader.o \
    $(CORE_DIR)/Core/core/loader/ncch.o \
    $(CORE_DIR)/Core/core/loader/artic.o \
    $(CORE_DIR)/Core/core/loader/smdh.o \
    $(CORE_DIR)/Core/core/loader/3dsx.o \
    $(CORE_DIR)/Core/core/frontend/emu_window.o \
    $(CORE_DIR)/Core/core/frontend/image_interface.o \
    $(CORE_DIR)/Core/core/frontend/framebuffer_layout.o \
    $(CORE_DIR)/Core/core/frontend/camera/interface.o \
    $(CORE_DIR)/Core/core/frontend/camera/blank_camera.o \
    $(CORE_DIR)/Core/core/frontend/camera/factory.o \
    $(CORE_DIR)/Core/core/frontend/applets/swkbd.o \
    $(CORE_DIR)/Core/core/frontend/applets/default_applets.o \
    $(CORE_DIR)/Core/core/frontend/applets/mii_selector.o \
    $(CORE_DIR)/Core/core/gdbstub/gdbstub.o \
    $(CORE_DIR)/Core/core/gdbstub/hio.o \
    $(CORE_DIR)/Core/core/tracer/recorder.o \
    $(CORE_DIR)/Core/core/cheats/gateway_cheat.o \
    $(CORE_DIR)/Core/core/cheats/cheats.o \
    $(CORE_DIR)/Core/core/cheats/cheat_base.o \
    $(CORE_DIR)/Core/core/hle/romfs.o \
    $(CORE_DIR)/Core/core/hle/mii.o \
    $(CORE_DIR)/Core/core/hle/applets/applet.o \
    $(CORE_DIR)/Core/core/hle/applets/swkbd.o \
    $(CORE_DIR)/Core/core/hle/applets/mint.o \
    $(CORE_DIR)/Core/core/hle/applets/erreula.o \
    $(CORE_DIR)/Core/core/hle/applets/mii_selector.o \
    $(CORE_DIR)/Core/core/hle/kernel/thread.o \
    $(CORE_DIR)/Core/core/hle/kernel/client_session.o \
    $(CORE_DIR)/Core/core/hle/kernel/ipc.o \
    $(CORE_DIR)/Core/core/hle/kernel/wait_object.o \
    $(CORE_DIR)/Core/core/hle/kernel/shared_memory.o \
    $(CORE_DIR)/Core/core/hle/kernel/mutex.o \
    $(CORE_DIR)/Core/core/hle/kernel/server_port.o \
    $(CORE_DIR)/Core/core/hle/kernel/address_arbiter.o \
    $(CORE_DIR)/Core/core/hle/kernel/semaphore.o \
    $(CORE_DIR)/Core/core/hle/kernel/hle_ipc.o \
    $(CORE_DIR)/Core/core/hle/kernel/event.o \
    $(CORE_DIR)/Core/core/hle/kernel/object.o \
    $(CORE_DIR)/Core/core/hle/kernel/handle_table.o \
    $(CORE_DIR)/Core/core/hle/kernel/session.o \
    $(CORE_DIR)/Core/core/hle/kernel/kernel.o \
    $(CORE_DIR)/Core/core/hle/kernel/client_port.o \
    $(CORE_DIR)/Core/core/hle/kernel/svc.o \
    $(CORE_DIR)/Core/core/hle/kernel/vm_manager.o \
    $(CORE_DIR)/Core/core/hle/kernel/process.o \
    $(CORE_DIR)/Core/core/hle/kernel/timer.o \
    $(CORE_DIR)/Core/core/hle/kernel/memory.o \
    $(CORE_DIR)/Core/core/hle/kernel/config_mem.o \
    $(CORE_DIR)/Core/core/hle/kernel/resource_limit.o \
    $(CORE_DIR)/Core/core/hle/kernel/shared_page.o \
    $(CORE_DIR)/Core/core/hle/kernel/server_session.o \
    $(CORE_DIR)/Core/core/hle/kernel/ipc_debugger/recorder.o \
    $(CORE_DIR)/Core/core/hle/service/service.o \
    $(CORE_DIR)/Core/core/hle/service/gsp/gsp_lcd.o \
    $(CORE_DIR)/Core/core/hle/service/gsp/gsp.o \
    $(CORE_DIR)/Core/core/hle/service/gsp/gsp_gpu.o \
    $(CORE_DIR)/Core/core/hle/service/mvd/mvd_std.o \
    $(CORE_DIR)/Core/core/hle/service/mvd/mvd.o \
    $(CORE_DIR)/Core/core/hle/service/qtm/qtm_u.o \
    $(CORE_DIR)/Core/core/hle/service/qtm/qtm.o \
    $(CORE_DIR)/Core/core/hle/service/qtm/qtm_c.o \
    $(CORE_DIR)/Core/core/hle/service/qtm/qtm_s.o \
    $(CORE_DIR)/Core/core/hle/service/qtm/qtm_sp.o \
    $(CORE_DIR)/Core/core/hle/service/boss/boss_p.o \
    $(CORE_DIR)/Core/core/hle/service/boss/boss.o \
    $(CORE_DIR)/Core/core/hle/service/boss/boss_u.o \
    $(CORE_DIR)/Core/core/hle/service/boss/online_service.o \
    $(CORE_DIR)/Core/core/hle/service/ssl/ssl_c.o \
    $(CORE_DIR)/Core/core/hle/service/fs/fs_user.o \
    $(CORE_DIR)/Core/core/hle/service/fs/directory.o \
    $(CORE_DIR)/Core/core/hle/service/fs/archive.o \
    $(CORE_DIR)/Core/core/hle/service/fs/file.o \
    $(CORE_DIR)/Core/core/hle/service/plgldr/plgldr.o \
    $(CORE_DIR)/Core/core/hle/service/mcu/mcu_hwc.o \
    $(CORE_DIR)/Core/core/hle/service/mcu/mcu.o \
    $(CORE_DIR)/Core/core/hle/service/pxi/dev.o \
    $(CORE_DIR)/Core/core/hle/service/pxi/pxi.o \
    $(CORE_DIR)/Core/core/hle/service/cfg/cfg_i.o \
    $(CORE_DIR)/Core/core/hle/service/cfg/cfg.o \
    $(CORE_DIR)/Core/core/hle/service/cfg/cfg_nor.o \
    $(CORE_DIR)/Core/core/hle/service/cfg/cfg_defaults.o \
    $(CORE_DIR)/Core/core/hle/service/cfg/cfg_u.o \
    $(CORE_DIR)/Core/core/hle/service/cfg/cfg_s.o \
    $(CORE_DIR)/Core/core/hle/service/apt/apt_u.o \
    $(CORE_DIR)/Core/core/hle/service/apt/apt_s.o \
    $(CORE_DIR)/Core/core/hle/service/apt/ns_s.o \
    $(CORE_DIR)/Core/core/hle/service/apt/apt.o \
    $(CORE_DIR)/Core/core/hle/service/apt/apt_a.o \
    $(CORE_DIR)/Core/core/hle/service/apt/ns_c.o \
    $(CORE_DIR)/Core/core/hle/service/apt/applet_manager.o \
    $(CORE_DIR)/Core/core/hle/service/apt/ns.o \
    $(CORE_DIR)/Core/core/hle/service/apt/bcfnt/bcfnt.o \
    $(CORE_DIR)/Core/core/hle/service/dlp/dlp_srvr.o \
    $(CORE_DIR)/Core/core/hle/service/dlp/dlp_fkcl.o \
    $(CORE_DIR)/Core/core/hle/service/dlp/dlp.o \
    $(CORE_DIR)/Core/core/hle/service/dlp/dlp_clnt.o \
    $(CORE_DIR)/Core/core/hle/service/news/news_u.o \
    $(CORE_DIR)/Core/core/hle/service/news/news.o \
    $(CORE_DIR)/Core/core/hle/service/news/news_s.o \
    $(CORE_DIR)/Core/core/hle/service/pm/pm_app.o \
    $(CORE_DIR)/Core/core/hle/service/pm/pm.o \
    $(CORE_DIR)/Core/core/hle/service/pm/pm_dbg.o \
    $(CORE_DIR)/Core/core/hle/service/ac/ac_i.o \
    $(CORE_DIR)/Core/core/hle/service/ac/ac_u.o \
    $(CORE_DIR)/Core/core/hle/service/ac/ac.o \
    $(CORE_DIR)/Core/core/hle/service/ptm/ptm_gets.o \
    $(CORE_DIR)/Core/core/hle/service/ptm/ptm_sets.o \
    $(CORE_DIR)/Core/core/hle/service/ptm/ptm.o \
    $(CORE_DIR)/Core/core/hle/service/ptm/ptm_u.o \
    $(CORE_DIR)/Core/core/hle/service/ptm/ptm_sysm.o \
    $(CORE_DIR)/Core/core/hle/service/ptm/ptm_play.o \
    $(CORE_DIR)/Core/core/hle/service/soc/soc_u.o \
    $(CORE_DIR)/Core/core/hle/service/dsp/dsp_dsp.o \
    $(CORE_DIR)/Core/core/hle/service/ir/extra_hid.o \
    $(CORE_DIR)/Core/core/hle/service/ir/ir.o \
    $(CORE_DIR)/Core/core/hle/service/ir/ir_u.o \
    $(CORE_DIR)/Core/core/hle/service/ir/ir_rst.o \
    $(CORE_DIR)/Core/core/hle/service/ir/ir_user.o \
    $(CORE_DIR)/Core/core/hle/service/cam/cam_c.o \
    $(CORE_DIR)/Core/core/hle/service/cam/cam_s.o \
    $(CORE_DIR)/Core/core/hle/service/cam/cam_u.o \
    $(CORE_DIR)/Core/core/hle/service/cam/y2r_u.o \
    $(CORE_DIR)/Core/core/hle/service/cam/cam.o \
    $(CORE_DIR)/Core/core/hle/service/cam/cam_q.o \
    $(CORE_DIR)/Core/core/hle/service/nim/nim.o \
    $(CORE_DIR)/Core/core/hle/service/nim/nim_s.o \
    $(CORE_DIR)/Core/core/hle/service/nim/nim_u.o \
    $(CORE_DIR)/Core/core/hle/service/nim/nim_aoc.o \
    $(CORE_DIR)/Core/core/hle/service/mic/mic_u.o \
    $(CORE_DIR)/Core/core/hle/service/csnd/csnd_snd.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_inf.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_tst.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_sap.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_soc.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_cec.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/uds_data.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_ext.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm_uds.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/uds_connection.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/nwm.o \
    $(CORE_DIR)/Core/core/hle/service/nwm/uds_beacon.o \
    $(CORE_DIR)/Core/core/hle/service/act/act.o \
    $(CORE_DIR)/Core/core/hle/service/act/act_a.o \
    $(CORE_DIR)/Core/core/hle/service/act/act_errors.o \
    $(CORE_DIR)/Core/core/hle/service/act/act_u.o \
    $(CORE_DIR)/Core/core/hle/service/err/err_f.o \
    $(CORE_DIR)/Core/core/hle/service/am/am_u.o \
    $(CORE_DIR)/Core/core/hle/service/am/am_net.o \
    $(CORE_DIR)/Core/core/hle/service/am/am.o \
    $(CORE_DIR)/Core/core/hle/service/am/am_app.o \
    $(CORE_DIR)/Core/core/hle/service/am/am_sys.o \
    $(CORE_DIR)/Core/core/hle/service/ndm/ndm_u.o \
    $(CORE_DIR)/Core/core/hle/service/frd/frd_a.o \
    $(CORE_DIR)/Core/core/hle/service/frd/frd_u.o \
    $(CORE_DIR)/Core/core/hle/service/frd/frd.o \
    $(CORE_DIR)/Core/core/hle/service/sm/sm.o \
    $(CORE_DIR)/Core/core/hle/service/sm/srv.o \
    $(CORE_DIR)/Core/core/hle/service/hid/hid_user.o \
    $(CORE_DIR)/Core/core/hle/service/hid/hid.o \
    $(CORE_DIR)/Core/core/hle/service/hid/hid_spvr.o \
    $(CORE_DIR)/Core/core/hle/service/ldr_ro/cro_helper.o \
    $(CORE_DIR)/Core/core/hle/service/ldr_ro/ldr_ro.o \
    $(CORE_DIR)/Core/core/hle/service/ps/ps_ps.o \
    $(CORE_DIR)/Core/core/hle/service/http/http_c.o \
    $(CORE_DIR)/Core/core/hle/service/nfc/amiibo_crypto.o \
    $(CORE_DIR)/Core/core/hle/service/nfc/nfc_device.o \
    $(CORE_DIR)/Core/core/hle/service/nfc/nfc.o \
    $(CORE_DIR)/Core/core/hle/service/nfc/nfc_u.o \
    $(CORE_DIR)/Core/core/hle/service/nfc/nfc_m.o \
    $(CORE_DIR)/Core/core/hle/service/cecd/cecd_u.o \
    $(CORE_DIR)/Core/core/hle/service/cecd/cecd.o \
    $(CORE_DIR)/Core/core/hle/service/cecd/cecd_s.o \
    $(CORE_DIR)/Core/core/hle/service/cecd/cecd_ndm.o \
    $(CORE_DIR)/Core/core/file_sys/archive_sdmc.o \
    $(CORE_DIR)/Core/core/file_sys/disk_archive.o \
    $(CORE_DIR)/Core/core/file_sys/path_parser.o \
    $(CORE_DIR)/Core/core/file_sys/delay_generator.o \
    $(CORE_DIR)/Core/core/file_sys/archive_backend.o \
    $(CORE_DIR)/Core/core/file_sys/archive_sdmcwriteonly.o \
    $(CORE_DIR)/Core/core/file_sys/secure_value_backend.o \
    $(CORE_DIR)/Core/core/file_sys/ivfc_archive.o \
    $(CORE_DIR)/Core/core/file_sys/patch.o \
    $(CORE_DIR)/Core/core/file_sys/romfs_reader.o \
    $(CORE_DIR)/Core/core/file_sys/secure_value_backend_artic.o \
    $(CORE_DIR)/Core/core/file_sys/artic_cache.o \
    $(CORE_DIR)/Core/core/file_sys/plugin_3gx.o \
    $(CORE_DIR)/Core/core/file_sys/archive_savedata.o \
    $(CORE_DIR)/Core/core/file_sys/otp.o \
    $(CORE_DIR)/Core/core/file_sys/ncch_container.o \
    $(CORE_DIR)/Core/core/file_sys/title_metadata.o \
    $(CORE_DIR)/Core/core/file_sys/ticket.o \
    $(CORE_DIR)/Core/core/file_sys/archive_systemsavedata.o \
    $(CORE_DIR)/Core/core/file_sys/savedata_archive.o \
    $(CORE_DIR)/Core/core/file_sys/certificate.o \
    $(CORE_DIR)/Core/core/file_sys/archive_ncch.o \
    $(CORE_DIR)/Core/core/file_sys/layered_fs.o \
    $(CORE_DIR)/Core/core/file_sys/archive_extsavedata.o \
    $(CORE_DIR)/Core/core/file_sys/archive_selfncch.o \
    $(CORE_DIR)/Core/core/file_sys/archive_other_savedata.o \
    $(CORE_DIR)/Core/core/file_sys/archive_source_sd_savedata.o \
    $(CORE_DIR)/Core/core/file_sys/archive_artic.o \
    $(CORE_DIR)/Core/core/file_sys/cia_container.o \
    $(CORE_DIR)/Core/core/file_sys/seed_db.o \
    $(CORE_DIR)/Core/core/dumping/backend.o \
    $(CORE_DIR)/Core/core/arm/exclusive_monitor.o \
    $(CORE_DIR)/Core/core/arm/hybrid_cpu.o \
    $(CORE_DIR)/Core/core/arm/dynarmic/arm_exclusive_monitor.o \
    $(CORE_DIR)/Core/core/arm/dynarmic/arm_tick_counts.o \
    $(CORE_DIR)/Core/core/arm/dynarmic/arm_hybrid.o \
    $(CORE_DIR)/Core/core/arm/dyncom/arm_dyncom_trans.o \
    $(CORE_DIR)/Core/core/arm/dyncom/arm_dyncom_interpreter.o \
    $(CORE_DIR)/Core/core/arm/dyncom/arm_dyncom_dec.o \
    $(CORE_DIR)/Core/core/arm/dyncom/arm_dyncom.o \
    $(CORE_DIR)/Core/core/arm/dyncom/arm_dyncom_thumb.o \
    $(CORE_DIR)/Core/core/arm/skyeye_common/armsupp.o \
    $(CORE_DIR)/Core/core/arm/skyeye_common/armstate.o \
    $(CORE_DIR)/Core/core/arm/skyeye_common/vfp/vfpinstr.o \
    $(CORE_DIR)/Core/core/arm/skyeye_common/vfp/vfpsingle.o \
    $(CORE_DIR)/Core/core/arm/skyeye_common/vfp/vfp.o \
    $(CORE_DIR)/Core/core/arm/skyeye_common/vfp/vfpdouble.o \
