EXTERNAL_OBJECTS := \
    /libretro/dynarmic/src/dynarmic/common/u128.o \
    /libretro/dynarmic/src/dynarmic/common/x64_disassemble.o \
    /libretro/dynarmic/src/dynarmic/common/spin_lock_x64.o \
    /libretro/dynarmic/src/dynarmic/common/memory_pool.o \
    /libretro/dynarmic/src/dynarmic/common/math_util.o \
    /libretro/dynarmic/src/dynarmic/common/spin_lock_arm64.o \
    /libretro/dynarmic/src/dynarmic/common/llvm_disassemble.o \
    /libretro/dynarmic/src/dynarmic/common/fp/fused.o \
    /libretro/dynarmic/src/dynarmic/common/fp/unpacked.o \
    /libretro/dynarmic/src/dynarmic/common/fp/process_exception.o \
    /libretro/dynarmic/src/dynarmic/common/fp/process_nan.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPRecipExponent.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPConvert.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPRecipStepFused.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPRecipEstimate.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPMulAdd.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPRoundInt.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPRSqrtStepFused.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPToFixed.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPCompare.o \
    /libretro/dynarmic/src/dynarmic/common/fp/op/FPRSqrtEstimate.o \
    /libretro/dynarmic/src/dynarmic/common/crypto/sm4.o \
    /libretro/dynarmic/src/dynarmic/common/crypto/aes.o \
    /libretro/dynarmic/src/dynarmic/common/crypto/crc32.o \
    /libretro/dynarmic/src/dynarmic/frontend/imm.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/a32_types.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/a32_location_descriptor.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/a32_ir_emitter.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/translate_thumb.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/a32_translate.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/conditional_state.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/translate_arm.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_register.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_control.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_branch.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_load_store_structures.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/multiply.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_word.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_crc32.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/extension.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/hint.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_shifted_register.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_translate_impl.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_three_regs.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_store_single_data_item.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb16.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/synchronization.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_store_multiple.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_two_regs_scalar.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_misc.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_halfword.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/barrier.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/vfp.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_modified_immediate.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_branch.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/parallel.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/status_register_access.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_coprocessor.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_exception_generating.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_plain_binary_immediate.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_parallel.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_byte.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/divide.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/reversal.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_long_multiply.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_two_regs_shift.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/data_processing.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/saturated.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_store_dual.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/coprocessor.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_one_reg_modified_immediate.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_multiply.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/misc.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/load_store.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/packing.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_two_regs_misc.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_misc.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/disassembler/disassembler_arm.o \
    /libretro/dynarmic/src/dynarmic/frontend/A32/disassembler/disassembler_thumb.o \
    /libretro/dynarmic/src/dynarmic/ir/microinstruction.o \
    /libretro/dynarmic/src/dynarmic/ir/location_descriptor.o \
    /libretro/dynarmic/src/dynarmic/ir/opcodes.o \
    /libretro/dynarmic/src/dynarmic/ir/type.o \
    /libretro/dynarmic/src/dynarmic/ir/basic_block.o \
    /libretro/dynarmic/src/dynarmic/ir/value.o \
    /libretro/dynarmic/src/dynarmic/ir/ir_emitter.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/a32_get_set_elimination_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/a64_get_set_elimination_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/identity_removal_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/a64_merge_interpret_blocks.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/a64_callback_config_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/verification_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/dead_code_elimination_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/constant_propagation_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/polyfill_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/naming_pass.o \
    /libretro/dynarmic/src/dynarmic/ir/opt/a32_constant_memory_reads_pass.o \
