EXTERNAL_OBJECTS := \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/u128.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/memory_pool.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/math_util.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/fused.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/unpacked.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/process_exception.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/process_nan.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPRecipExponent.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPConvert.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPRecipStepFused.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPRecipEstimate.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPMulAdd.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPRoundInt.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPRSqrtStepFused.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPToFixed.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPCompare.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/fp/op/FPRSqrtEstimate.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/crypto/sm4.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/crypto/aes.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/common/crypto/crc32.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/imm.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/a32_types.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/a32_location_descriptor.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/a32_ir_emitter.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/translate_thumb.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/a32_translate.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/conditional_state.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/translate_arm.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_register.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_control.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_branch.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_load_store_structures.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/multiply.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_word.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_crc32.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/extension.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/hint.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_shifted_register.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_translate_impl.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_three_regs.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_store_single_data_item.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb16.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/synchronization.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_store_multiple.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_two_regs_scalar.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_misc.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_halfword.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/barrier.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/vfp.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_modified_immediate.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_branch.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/parallel.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/status_register_access.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_coprocessor.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/a32_exception_generating.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_data_processing_plain_binary_immediate.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_parallel.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_byte.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/divide.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/reversal.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_long_multiply.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_two_regs_shift.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/data_processing.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/saturated.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_load_store_dual.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/coprocessor.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_one_reg_modified_immediate.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/thumb32_multiply.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/misc.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/load_store.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/packing.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_two_regs_misc.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/frontend/A32/translate/impl/asimd_misc.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/microinstruction.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/location_descriptor.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opcodes.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/type.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/basic_block.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/value.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/ir_emitter.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/a32_get_set_elimination_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/identity_removal_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/verification_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/dead_code_elimination_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/constant_propagation_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/polyfill_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/naming_pass.o \
    $(CORE_DIR)/libretro/dynarmic/src/dynarmic/ir/opt/a32_constant_memory_reads_pass.o \
    $(CORE_DIR)/libretro/dynarmic/externals/mcl/src/assert.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/btdmp.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/dma.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/parser.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/processor.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/teakra_c.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/memory_interface.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/ahbm.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/mmio.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/test_generator.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/timer.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/apbp.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/disassembler.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/teakra.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/disassembler_c.o \
    $(CORE_DIR)/libretro/azahar/externals/teakra/src/makedsp1/sha256.o \
    $(CORE_DIR)/libretro/azahar/externals/fmt/src/format.o \
    $(CORE_DIR)/libretro/azahar/externals/fmt/src/os.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/xxhash.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/entropy_common.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/zstd_common.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/pool.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/threading.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/error_private.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/debug.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/common/fse_decompress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_opt.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_lazy.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_double_fast.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/hist.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_compress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_compress_sequences.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_preSplit.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_compress_superblock.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_ldm.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/fse_compress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/huf_compress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstdmt_compress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_fast.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/compress/zstd_compress_literals.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/decompress/zstd_ddict.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/decompress/zstd_decompress_block.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/decompress/zstd_decompress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/lib/decompress/huf_decompress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/contrib/seekable_format/zstdseek_compress.o \
    $(CORE_DIR)/libretro/azahar/externals/zstd/contrib/seekable_format/zstdseek_decompress.o \
    $(CORE_DIR)/libretro/azahar/externals/lodepng/lodepng/lodepng.o \
    $(CORE_DIR)/libretro/azahar/externals/lodepng/lodepng/lodepng_util.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_grammar.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_text_oprimitive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_woarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_xml_woarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_oserializer.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/extended_type_info_no_rtti.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/binary_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_text_woarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/binary_wiarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/text_wiarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/archive_exception.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_pointer_iserializer.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/codecvt_null.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/extended_type_info.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_text_wiprimitive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/text_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_text_iprimitive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/binary_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_serializer_map.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/text_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/void_cast.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_xml_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_text_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/extended_type_info_typeid.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/text_woarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_binary_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_xml_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_binary_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/stl_port.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_text_woprimitive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/utf8_codecvt_facet.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_xml_archive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_archive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_oarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_archive_exception.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_pointer_oserializer.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_xml_wiarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_text_iarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_wgrammar.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/binary_woarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/basic_iserializer.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/polymorphic_text_wiarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/serialization/src/xml_wiarchive.o \
    $(CORE_DIR)/libretro/azahar/externals/boost/libs/iostreams/src/file_descriptor.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/tiger.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rabbit.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/blowfish.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/pssr.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/whrlpool.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/3way.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cham_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ttmac.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/iterhash.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/marss.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/simeck.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cpu.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/square.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sm4.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/kalyna.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/keccak_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/threefish.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/xed25519.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/speck.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/filters.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rabin.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/channels.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sha_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/basecode.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/zlib.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ariatab.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/serpent.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/adler32.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/dll.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/wake.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/primetab.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rijndael.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/dessp.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/zdeflate.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/pubkey.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/crc_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/lea_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/fips140.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ecp.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/chachapoly.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/files.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/hight.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cryptlib.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rw.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sosemanuk.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/chacha.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cast.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/shacal2.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/authenc.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/casts.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/pch.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/seal.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/simon.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rsa.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/safer.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gfpcrypt.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/nbtheory.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/mars.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ripemd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gf2_32.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/dh.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/asn.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/hc256.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/eccrypto.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/tigertab.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/osrng.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/squaretb.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/donna_32.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/keccak.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/speck128_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/poly1305.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/base32.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rc6.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/hc128.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cham.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/dsa.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cbcmac.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/idea.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/arc4.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/tftables.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/algebra.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/modes.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rdrand.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/mqueue.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sm4_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ida.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/lsh256.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sharkbox.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gcm.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/zinflate.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/simon128_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ccm.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rdtables.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sse_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/shacal2_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/xts.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/simple.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/md2.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sha.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/fipsalgt.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/lea.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/kalynatab.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/polynomi.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gzip.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rng.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/chacha_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/xtr.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/eprecomp.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/donna_64.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/allocate.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/vmac.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/blake2s_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/padlkrng.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/blake2b_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/shark.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/cmac.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/bfinit.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/salsa.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/darn.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rc2.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/default.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gcm_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/scrypt.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/esign.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gost.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sm3.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/eax.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/twofish.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/strciphr.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/tea.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rijndael_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/pkcspad.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/elgamal.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/hmac.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/algparam.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gf2n.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/queue.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/skipjack.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/hex.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gf256.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/panama.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/keccak_core.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/ec2n.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/mqv.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/shake.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/des.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/sha3.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/lsh512.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/dh2.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/md5.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/rc5.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/integer.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/blumshub.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/tweetnacl.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/base64.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/aria.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/misc.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/blake2.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/seed.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/md4.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/hrtimer.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/emsa2.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/luc.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/oaep.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/randpool.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/crc.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/gf2n_simd.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/xtrcrypt.o \
    $(CORE_DIR)/libretro/azahar/externals/cryptopp/camellia.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/SoundTouch.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/FIFOSampleBuffer.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/RateTransposer.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/TDStretch.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/InterpolateLinear.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/InterpolateCubic.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/InterpolateShannon.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/AAFilter.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/PeakFinder.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/BPMDetect.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/FIRFilter.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/cpu_detect_x86.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/sse_optimized.o \
    $(CORE_DIR)/libretro/azahar/externals/soundtouch/source/SoundTouch/mmx_optimized.o \
    $(CORE_DIR)/libretro/libretro-common/file/file_path.o \
    $(CORE_DIR)/libretro/libretro-common/file/file_path_io.o \
    $(CORE_DIR)/libretro/libretro-common/streams/file_stream.o \
    $(CORE_DIR)/libretro/libretro-common/vfs/vfs_implementation.o \
    $(CORE_DIR)/libretro/libretro-common/compat/fopen_utf8.o \
    $(CORE_DIR)/libretro/libretro-common/encodings/encoding_utf.o \
    $(CORE_DIR)/libretro/libretro-common/file/retro_dirent.o \
    $(CORE_DIR)/libretro/libretro-common/streams/file_stream_transforms.o \
    $(CORE_DIR)/libretro/libretro-common/string/stdstring.o \
    $(CORE_DIR)/libretro/libretro-common/time/rtime.o \
    $(CORE_DIR)/libretro/libretro-common/compat/compat_strl.o \
